excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mareynolds.github.io
title: Co-op Board Game Reviews by Matt
tagline: Making Every Day Game Day
description: My awesome new site where I review cooperative tabletop games. 
paginate: 5
